### ISSUE TITLE
Error When connecting to Firebase

### ISSUE THREAD

**Issue by LadyDeathKZN** [c4software/firebase-realtime-maps-sample#1]
Hi,  I get this error when I connect to my firebase via the config. You also havent provided the set up to how the firebase should look.

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'lat' of null"

found in

---> <LMarker>
       <LMap>
         <MyMap> at src/view/map.vue
           <App> at src/App.vue
             <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1862
callHook @ vue.runtime.esm.js?2b0e:4219
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6346
patch @ vue.runtime.esm.js?2b0e:6565
Vue._update @ vue.runtime.esm.js?2b0e:3948
updateComponent @ vue.runtime.esm.js?2b0e:4066
get @ vue.runtime.esm.js?2b0e:4479
run @ vue.runtime.esm.js?2b0e:4554
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4310
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4402
update @ vue.runtime.esm.js?2b0e:4544
notify @ vue.runtime.esm.js?2b0e:730
mutator @ vue.runtime.esm.js?2b0e:882
eval @ vuefire.js?5f30:197
eval @ index.cjs.js?3523:4594
exceptionGuard @ index.cjs.js?3523:694
EventList.raise @ index.cjs.js?3523:9771
EventQueue.raiseQueuedEventsMatchingPredicate_ @ index.cjs.js?3523:9725
EventQueue.raiseEventsForChangedPath @ index.cjs.js?3523:9709
Repo.onDataUpdate_ @ index.cjs.js?3523:12825
PersistentConnection.onDataPush_ @ index.cjs.js?3523:12121
PersistentConnection.onDataMessage_ @ index.cjs.js?3523:12115
Connection.onDataMessage_ @ index.cjs.js?3523:11390
Connection.onPrimaryMessageReceived_ @ index.cjs.js?3523:11384
eval @ index.cjs.js?3523:11285
WebSocketConnection.appendFrame_ @ index.cjs.js?3523:10888
WebSocketConnection.handleIncomingFrame @ index.cjs.js?3523:10938
mySock.onmessage @ index.cjs.js?3523:10835
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'lat' of null
    at Object.project (leaflet-src.js?e11e:1659)
    at Object.latLngToPoint (leaflet-src.js?e11e:1498)
    at NewClass.project (leaflet-src.js?e11e:3901)
    at NewClass.latLngToLayerPoint (leaflet-src.js?e11e:3923)
    at NewClass.update (leaflet-src.js?e11e:7440)
    at NewClass.onAdd (leaflet-src.js?e11e:7365)
    at NewClass._layerAdd (leaflet-src.js?e11e:6487)
    at NewClass.whenReady (leaflet-src.js?e11e:4367)
    at NewClass.addLayer (leaflet-src.js?e11e:6549)
    at VueComponent.addLayer (vue2-leaflet.min.js?458e:1)

**Comment by c4software** [comment]
Hi.

Interesting. I look at it today

**Comment by c4software** [comment]
Hi,

I upgrade third party library and make this sample working again. 

Happy coding.
